### ISSUE TITLE
Windows cache restore failure

### ISSUE THREAD

**Issue by wpbonelli** [modflowpy/install-intelfortran-action#7]
As reported [here](https://github.com/MODFLOW-USGS/modflow6/issues/1054) the cache can fail to restore on Windows due to a path not found error. ~~A look at the missing paths (e.g. `/c/Program Files (x86)/Intel/oneAPI/compiler/2022.1.0/windows/compiler/lib/ia32_win`) indicates it may be caused by [excluding unused files](https://github.com/modflowpy/install-intelfortran-action/blob/a1809368dc9b35436b1c6e0a5cc4884e4e7558d7/action.yml#L168)~~

**Comment by wpbonelli** [comment]
~~After a second look it seems this only happens when this action is used in the same job as the `mamba-org/provision-with-micromamba` action. The problem does not occur with pip environments or with miniconda.~~

**Comment by sanguinariojoe** [comment]
Cache is also failing to me... Apparently it is unpacked in ${{github.workspace}}/ instead of /c/Program Files (x86)/

For the time being I just copied your code and strip the cache part, so it is installing it every single time

**Comment by wpbonelli** [comment]
@sanguinariojoe thanks for the report, would you mind linking an example workflow run?

**Comment by sanguinariojoe** [comment]
Sure!

- Not working: https://github.com/sanguinariojoe/MoorDyn/actions/runs/3273134559
- I suppose will be working (Still in progress, but it worked before): https://github.com/sanguinariojoe/MoorDyn/actions/runs/3273534330/jobs/5385863752

**Comment by wpbonelli** [comment]
The [cache restore failure](https://github.com/MODFLOW-USGS/modflow6/actions/runs/3113214744/jobs/5047564396#step:5:38) seems to have been because GNU tar, located at `C:\Program Files\Git\usr\bin\tar.exe` on Windows runners, [can't handle symlinks on Windows](https://superuser.com/questions/1465200/symbolic-link-issue-extracting-tarball-on-windows) (path adjustments caused this to be selected instead of the default `C:\Windows\System32\tar.exe`). #9 makes sure the default `tar.exe` is used, and also saves the cache if install succeeds, even if the workflow fails &mdash; this avoids situations where the default `actions/cache` behavior (not to save the cache until the `post` step after the workflow succeeds) can delay initial debugging of a new workflow. There is a separate [Micromamba compatibility note](https://github.com/modflowpy/install-intelfortran-action/blob/eecb7381303ad35d6b65053ca09fc999711ea3ee/README.md#micromamba-scripts) now documented in the README too.

These issues seems unrelated to what you're seeing [here](https://github.com/sanguinariojoe/MoorDyn/actions/runs/3273134559/jobs/5385110228#step:10:41) though, please feel free to open a new issue after this one is closed if the update doesn't solve things for you

**Comment by sanguinariojoe** [comment]
I will check the update ASAP and let you know
